name: pomodoro_app
description: Pomodoro App.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  bloc: 8.1.0
  cupertino_icons: 1.0.2
  curved_navigation_bar: 1.0.3
  equatable: 2.0.5
  floor: 1.4.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  get_it: 7.2.0
  sqflite: 2.0.3

dev_dependencies:
  build_runner: 2.2.0
  floor_generator: 1.3.0
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
